# Generated by Django 4.2.2 on 2023-07-08 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(10)),
        ),
    ]
